MAIL_ERROR_SUBJECT = '[Dev Auth] Application Error'
PAYU_URL = 'https://staging.payu.co.za/rpp.do'
PAYU_USERNAME = 'Staging Integration Store 3'
PAYU_WSDL = 'https://staging.payu.co.za/service/PayUAPI?wsdl'
SECRET_KEY = 'a-good-secret-is-hard-to-find'
SECURITY_PASSWORD_SALT = 'salt-in-the-wounds'
SQLALCHEMY_DATABASE_URI = 'sqlite:///../instance/data/development.db'
