MAIL_SERVER = 'localhost'
MAIL_DEFAULT_SENDER_NAME = 'Test Auth'
MAIL_DEFAULT_SENDER_EMAIL = 'no-reply@test.example.com'
SECRET_KEY = 'a-good-secret-is-hard-to-find'
SECURITY_PASSWORD_SALT = 'salt-in-the-wounds'
TESTING = True
WTF_CSRF_ENABLED = False
WTF_CSRF_METHODS = []
SQLALCHEMY_DATABASE_URI = 'sqlite:///../data/test.db'
