MAIL_DEFAULT_SENDER = 'Test Auth <no-reply@test.example.com>'
MAIL_PORT = 25
MAIL_SERVER = 'localhost'
SECRET_KEY = 'a-good-secret-is-hard-to-find'
SECURITY_PASSWORD_SALT = 'salt-in-the-wounds'
TESTING = True
WTF_CSRF_ENABLED = False
WTF_CSRF_METHODS = []
SQLALCHEMY_DATABASE_URI = 'sqlite:///../data/test.db'
