"""empty message

Revision ID: 1a8af5801a73
Revises: a867bdb247c3
Create Date: 2016-02-03 11:17:17.038709

"""

# revision identifiers, used by Alembic.
revision = '1a8af5801a73'
down_revision = 'a867bdb247c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('products', sa.Column('gateway_id', sa.Unicode(length=20), nullable=True))
    op.add_column('products', sa.Column('network_id', sa.Unicode(length=20), nullable=False))
    op.add_column('products', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'products', 'gateways', ['gateway_id'], ['id'], onupdate='cascade')
    op.create_foreign_key(None, 'products', 'networks', ['network_id'], ['id'], onupdate='cascade')
    op.create_unique_constraint('network_id_email', 'users', ['network_id', 'email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('network_id_email', 'users', type_='unique')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'status')
    op.drop_column('products', 'network_id')
    op.drop_column('products', 'gateway_id')
    op.drop_column('products', 'created_at')
    ### end Alembic commands ###
