"""empty message

Revision ID: a867bdb247c3
Revises: None
Create Date: 2016-01-30 13:13:20.013771

"""

# revision identifiers, used by Alembic.
revision = 'a867bdb247c3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('login_ask_name', sa.Boolean(), nullable=True))
    op.add_column('vouchers', sa.Column('name', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'name')
    op.drop_column('gateways', 'login_ask_name')
    ### end Alembic commands ###
