from auth.blueprints.category import category
from auth.blueprints.country import country
from auth.blueprints.gateway import gateway
from auth.blueprints.network import network
from auth.blueprints.order import order
from auth.blueprints.product import product
from auth.blueprints.user import user
from auth.blueprints.voucher import voucher
from auth.blueprints.wifidog import wifidog
